In [2]:
spark

In [3]:
## CRIAR RDD

In [5]:
rdd = sc.textFile('/bases/base.csv')

In [6]:
rdd.take(5)

['usuario,item,avaliacao', '109,9,3', '174,412,1', '7,208,5', '371,97,5']

In [7]:
## DATAFRAME

In [11]:
df_csv = spark.read.csv(path='/bases/base.csv',header=True,sep=',')

In [9]:
type(df_csv)

pyspark.sql.dataframe.DataFrame

In [16]:
df_csv.show()

+-------+----+---------+
|usuario|item|avaliacao|
+-------+----+---------+
|    109|   9|        3|
|    174| 412|        1|
|      7| 208|        5|
|    371|  97|        5|
|    296| 255|        2|
|    280|  82|        2|
|    271| 275|        4|
|    110| 791|        2|
|     59| 926|        1|
|    217| 576|        1|
|    145| 665|        5|
|    334| 204|        4|
|     42| 568|        4|
|    200| 143|        5|
|     89| 387|        5|
|    311| 588|        4|
|    235| 269|        4|
|    287| 156|        5|
|    344| 204|        4|
|     43| 289|        4|
+-------+----+---------+
only showing top 20 rows

In [17]:
df_csv.count()

100000

In [18]:
df_json = spark.read.json('/bases/pessoas.json')

In [19]:
df_json.show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [20]:
df_json.count()

100

In [21]:
help(df_json.filter)

Help on method filter in module pyspark.sql.dataframe:

filter(condition) method of pyspark.sql.dataframe.DataFrame instance
    Filters rows using the given condition.

    :func:`where` is an alias for :func:`filter`.

    :param condition: a :class:`Column` of :class:`types.BooleanType`
        or a string of SQL expression.

    >>> df.filter(df.age > 3).collect()
    [Row(age=5, name='Bob')]
    >>> df.where(df.age == 2).collect()
    [Row(age=2, name='Alice')]

    >>> df.filter("age > 3").collect()
    [Row(age=5, name='Bob')]
    >>> df.where("age = 2").collect()
    [Row(age=2, name='Alice')]

    .. versionadded:: 1.3

In [25]:
df_json.where(df_json.age < 3).show()

+---+---+--------+
|age| id|    name|
+---+---+--------+
|  1| 85|Leonardo|
|  1| 88|    Gael|
|  1| 89| Antônio|
+---+---+--------+

In [26]:
df_json.where('age < 3').show()

+---+---+--------+
|age| id|    name|
+---+---+--------+
|  1| 85|Leonardo|
|  1| 88|    Gael|
|  1| 89| Antônio|
+---+---+--------+

In [27]:
df_menor3 = df_json.filter(df_json.age < 3)

In [28]:
df_menor3.show()

+---+---+--------+
|age| id|    name|
+---+---+--------+
|  1| 85|Leonardo|
|  1| 88|    Gael|
|  1| 89| Antônio|
+---+---+--------+

In [29]:
df_json.show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [31]:
import pandas as pd

In [32]:
df_pandas = df_json.toPandas()

In [33]:
type(df_pandas)

pandas.core.frame.DataFrame

In [34]:
type(df_json)

pyspark.sql.dataframe.DataFrame

In [37]:
df_maior = df_json.where(df_json.age >= 18)

In [40]:
df_maior.show(2)

+---+---+------+
|age| id|  name|
+---+---+------+
| 28|  1|Helena|
| 44|  2|Miguel|
+---+---+------+
only showing top 2 rows

In [41]:
df_menor = df_json.filter(df_json.age < 18)

In [42]:
df_menor.show(2)

+---+---+-------+
|age| id|   name|
+---+---+-------+
|  4| 26|Isadora|
|  7| 38|    Liz|
+---+---+-------+
only showing top 2 rows

In [45]:
df_union = df_maior.union(df_menor)

In [46]:
df_dup = df_json.unionAll(df_union)

In [47]:
df_dup.orderBy('id',ascending=True).show()

+---+---+---------+
|age| id|     name|
+---+---+---------+
| 28|  1|   Helena|
| 28|  1|   Helena|
| 44|  2|   Miguel|
| 44|  2|   Miguel|
| 97|  3|    Alice|
| 97|  3|    Alice|
| 28|  4|    Laura|
| 28|  4|    Laura|
| 94|  5|  Manuela|
| 94|  5|  Manuela|
| 71|  6|Valentina|
| 71|  6|Valentina|
| 48|  7|   Sophia|
| 48|  7|   Sophia|
| 98|  8| Isabella|
| 98|  8| Isabella|
| 60|  9|  Heloísa|
| 60|  9|  Heloísa|
| 46| 10|    Luiza|
| 46| 10|    Luiza|
+---+---+---------+
only showing top 20 rows

In [48]:
df_limpo = df_dup.dropDuplicates()

In [49]:
df_limpo.orderBy('id',ascending=True).show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [50]:
help(df_dup.dropDuplicates)

Help on method dropDuplicates in module pyspark.sql.dataframe:

dropDuplicates(subset=None) method of pyspark.sql.dataframe.DataFrame instance
    Return a new :class:`DataFrame` with duplicate rows removed,
    optionally only considering certain columns.

    For a static batch :class:`DataFrame`, it just drops duplicate rows. For a streaming
    :class:`DataFrame`, it will keep all data across triggers as intermediate state to drop
    duplicates rows. You can use :func:`withWatermark` to limit how late the duplicate data can
    be and system will accordingly limit the state. In addition, too late data older than
    watermark will be dropped to avoid any possibility of duplicates.

    :func:`drop_duplicates` is an alias for :func:`dropDuplicates`.

    >>> from pyspark.sql import Row
    >>> df = sc.parallelize([ \
    ...     Row(name='Alice', age=5, height=80), \
    ...     Row(name='Alice', age=5, height=80), \
    ...     Row(name='Alice', age=10, height=80)]).toDF()
    >>> df.dropDuplicates().show()
    +---+------+-----+
    |age|height| name|
    +---+------+-----+
    |  5|    80|Alice|
    | 10|    80|Alice|
    +---+------+-----+

    >>> df.dropDuplicates(['name', 'height']).show()
    +---+------+-----+
    |age|height| name|
    +---+------+-----+
    |  5|    80|Alice|
    +---+------+-----+

    .. versionadded:: 1.4

In [51]:
df_name = df_json.select('name','age')

In [52]:
df_name.show()

+-------------+---+
|         name|age|
+-------------+---+
|       Helena| 28|
|       Miguel| 44|
|        Alice| 97|
|        Laura| 28|
|      Manuela| 94|
|    Valentina| 71|
|       Sophia| 48|
|     Isabella| 98|
|      Heloísa| 60|
|        Luiza| 46|
|        Júlia| 47|
|       Lorena| 35|
|        Lívia| 32|
|  Maria Luiza| 90|
|      Cecília| 88|
|         Eloá| 36|
|     Giovanna| 57|
|  Maria Clara| 75|
|Maria Eduarda| 97|
|      Mariana| 65|
+-------------+---+
only showing top 20 rows

In [56]:
df_json \
    .select('name','age') \
    .filter(df_json.age > 72) \
    .orderBy('age',ascending=False) \
    .show(20,False)

+-------------+---+
|name         |age|
+-------------+---+
|Isabella     |98 |
|Maria Eduarda|97 |
|Alice        |97 |
|Gabriel      |97 |
|Clara        |95 |
|Manuela      |94 |
|Ana Laura    |93 |
|Ana Luiza    |92 |
|Antonella    |91 |
|Pietro       |91 |
|Elisa        |90 |
|Maria Luiza  |90 |
|Lorenzo      |89 |
|Vicente      |89 |
|Lara         |89 |
|Cecília      |88 |
|Maria Alice  |86 |
|Catarina     |84 |
|Isis         |83 |
|Lavínia      |82 |
+-------------+---+
only showing top 20 rows

In [64]:
df_maior.join(df_json,df_maior.id == df_json.id,'inner').show()

+---+---+-------------+---+---+-------------+
|age| id|         name|age| id|         name|
+---+---+-------------+---+---+-------------+
| 28|  1|       Helena| 28|  1|       Helena|
| 44|  2|       Miguel| 44|  2|       Miguel|
| 97|  3|        Alice| 97|  3|        Alice|
| 28|  4|        Laura| 28|  4|        Laura|
| 94|  5|      Manuela| 94|  5|      Manuela|
| 71|  6|    Valentina| 71|  6|    Valentina|
| 48|  7|       Sophia| 48|  7|       Sophia|
| 98|  8|     Isabella| 98|  8|     Isabella|
| 60|  9|      Heloísa| 60|  9|      Heloísa|
| 46| 10|        Luiza| 46| 10|        Luiza|
| 47| 11|        Júlia| 47| 11|        Júlia|
| 35| 12|       Lorena| 35| 12|       Lorena|
| 32| 13|        Lívia| 32| 13|        Lívia|
| 90| 14|  Maria Luiza| 90| 14|  Maria Luiza|
| 88| 15|      Cecília| 88| 15|      Cecília|
| 36| 16|         Eloá| 36| 16|         Eloá|
| 57| 17|     Giovanna| 57| 17|     Giovanna|
| 75| 18|  Maria Clara| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda| 97| 19|Maria Eduarda|
| 65| 20|      Mariana| 65| 20|      Mariana|
+---+---+-------------+---+---+-------------+
only showing top 20 rows

In [73]:
df_maior1= df_maior \
    .withColumn('name2',df_maior.name) \
    .withColumnRenamed('name','nome') \
    .withColumnRenamed('age','idade') \
    .withColumnRenamed('id','chave') \
    .select('chave','nome','idade','name2')

In [76]:
df_maior1.drop('name2').show()

+-----+-------------+-----+
|chave|         nome|idade|
+-----+-------------+-----+
|    1|       Helena|   28|
|    2|       Miguel|   44|
|    3|        Alice|   97|
|    4|        Laura|   28|
|    5|      Manuela|   94|
|    6|    Valentina|   71|
|    7|       Sophia|   48|
|    8|     Isabella|   98|
|    9|      Heloísa|   60|
|   10|        Luiza|   46|
|   11|        Júlia|   47|
|   12|       Lorena|   35|
|   13|        Lívia|   32|
|   14|  Maria Luiza|   90|
|   15|      Cecília|   88|
|   16|         Eloá|   36|
|   17|     Giovanna|   57|
|   18|  Maria Clara|   75|
|   19|Maria Eduarda|   97|
|   20|      Mariana|   65|
+-----+-------------+-----+
only showing top 20 rows

In [78]:
df_json.filter(df_json.name.like('%z%')).show()

+---+---+------------+
|age| id|        name|
+---+---+------------+
| 46| 10|       Luiza|
| 90| 14| Maria Luiza|
| 55| 22|     Beatriz|
| 92| 29|   Ana Luiza|
|  7| 38|         Liz|
| 89| 57|     Lorenzo|
|  6| 69|        Enzo|
|  3| 76|Enzo Gabriel|
+---+---+------------+

In [79]:
df_json.filter(df_json.name.startswith('A')).show()

+---+---+---------+
|age| id|     name|
+---+---+---------+
| 97|  3|    Alice|
| 91| 23|Antonella|
| 55| 27|Ana Clara|
| 92| 29|Ana Luiza|
| 23| 30|Ana Júlia|
| 25| 41|   Alícia|
| 93| 47|Ana Laura|
| 81| 49|   Agatha|
| 67| 52|   Arthur|
| 81| 81|  Anthony|
|  1| 89|  Antônio|
+---+---+---------+

In [80]:
df_json.filter(df_json.name.endswith('A')).show()

+---+---+----+
|age| id|name|
+---+---+----+
+---+---+----+

In [82]:
df_json.filter(df_json.age.between(1,5)).orderBy('age').show()

+---+---+------------+
|age| id|        name|
+---+---+------------+
|  1| 88|        Gael|
|  1| 85|    Leonardo|
|  1| 89|     Antônio|
|  3| 76|Enzo Gabriel|
|  3| 48|Maria Helena|
|  4| 26|     Isadora|
+---+---+------------+

In [86]:
df_json.groupBy('age').count().orderBy('count').show()

+---+-----+
|age|count|
+---+-----+
|  4|    1|
| 94|    1|
| 75|    1|
| 71|    1|
| 61|    1|
| 11|    1|
|  8|    1|
| 29|    1|
| 98|    1|
| 52|    1|
| 68|    1|
|  7|    1|
| 83|    1|
| 26|    1|
| 88|    1|
| 95|    1|
| 84|    1|
| 56|    1|
| 17|    1|
| 77|    1|
+---+-----+
only showing top 20 rows

In [89]:
df_maior.write.csv('/bases/export/csv',header=True,sep=',',mode='overwrite')

In [90]:
df_maior.write.json('/bases/export/json')

In [103]:
df_maior.write.parquet('/bases/export/parquet',compression='gzip',mode='append')

In [107]:
df_parquet = spark.read.parquet('/bases/export/parquet/part-00000-34e9a8c9-17f0-484a-89e8-69e3e73db5c6-c000.gz.parquet')

In [108]:
df_parquet.count()

82

In [113]:
df_maior.write.mode('append').format('hive').saveAsTable('default.19ABD2')

In [116]:
df_maior.write.mode('append').insertInto('default.19ABD2')

In [117]:
df_tab = spark.read.table('default.19ABD2')

In [118]:
df_tab.show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [119]:
df_query = sql('select * from default.19ABD2')

In [120]:
df_query.show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [121]:
sql('select * from default.19ABD2').show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [124]:
df_parquet.union(df_json.union(df_query)).show()

+---+---+-------------+
|age| id|         name|
+---+---+-------------+
| 28|  1|       Helena|
| 44|  2|       Miguel|
| 97|  3|        Alice|
| 28|  4|        Laura|
| 94|  5|      Manuela|
| 71|  6|    Valentina|
| 48|  7|       Sophia|
| 98|  8|     Isabella|
| 60|  9|      Heloísa|
| 46| 10|        Luiza|
| 47| 11|        Júlia|
| 35| 12|       Lorena|
| 32| 13|        Lívia|
| 90| 14|  Maria Luiza|
| 88| 15|      Cecília|
| 36| 16|         Eloá|
| 57| 17|     Giovanna|
| 75| 18|  Maria Clara|
| 97| 19|Maria Eduarda|
| 65| 20|      Mariana|
+---+---+-------------+
only showing top 20 rows

In [125]:
df_mysql = spark.read \
    .format('jdbc') \
    .option('url','jdbc:mysql://database/employees') \
    .option('driver','com.mysql.jdbc.Driver') \
    .option('dbtable','employees') \
    .option('user','root') \
    .option('password','secret') \
    .load()

In [127]:
df_mysql.count()

300024

In [128]:
df_mysql.write \
    .format('jdbc') \
    .option('url','jdbc:mysql://database/employees') \
    .option('driver','com.mysql.jdbc.Driver') \
    .option('dbtable','employees_19abd') \
    .option('user','root') \
    .option('password','secret') \
    .save()

In [129]:
df_mysql.write.parquet('/bases/export/employees')

In [130]:
import requests

In [131]:
r = requests.get('https://coronavirus-19-api.herokuapp.com/countries')

In [132]:
r.json()

[{'country': 'World',
  'cases': 255058048,
  'todayCases': 485347,
  'deaths': 5129233,
  'todayDeaths': 7114,
  'recovered': 230574466,
  'active': 19354349,
  'critical': 78026,
  'casesPerOneMillion': 32722,
  'deathsPerOneMillion': 658,
  'totalTests': 0,
  'testsPerOneMillion': 0},
 {'country': 'USA',
  'cases': 48160462,
  'todayCases': 86218,
  'deaths': 786236,
  'todayDeaths': 1250,
  'recovered': 38139829,
  'active': 9234397,
  'critical': 11412,
  'casesPerOneMillion': 144336,
  'deathsPerOneMillion': 2356,
  'totalTests': 725352987,
  'testsPerOneMillion': 2173863},
 {'country': 'India',
  'cases': 34456401,
  'todayCases': 0,
  'deaths': 463852,
  'todayDeaths': 0,
  'recovered': 33861756,
  'active': 130793,
  'critical': 8944,
  'casesPerOneMillion': 24636,
  'deathsPerOneMillion': 332,
  'totalTests': 625774159,
  'testsPerOneMillion': 447415},
 {'country': 'Brazil',
  'cases': 21965684,
  'todayCases': 4918,
  'deaths': 611524,
  'todayDeaths': 140,
  'recovered': 21177367,
  'active': 176793,
  'critical': 8318,
  'casesPerOneMillion': 102339,
  'deathsPerOneMillion': 2849,
  'totalTests': 63776166,
  'testsPerOneMillion': 297137},
 {'country': 'UK',
  'cases': 9637190,
  'todayCases': 37243,
  'deaths': 143159,
  'todayDeaths': 214,
  'recovered': 7903418,
  'active': 1590613,
  'critical': 999,
  'casesPerOneMillion': 140944,
  'deathsPerOneMillion': 2094,
  'totalTests': 348362751,
  'testsPerOneMillion': 5094802},
 {'country': 'Russia',
  'cases': 9145912,
  'todayCases': 36818,
  'deaths': 257837,
  'todayDeaths': 1240,
  'recovered': 7846448,
  'active': 1041627,
  'critical': 2300,
  'casesPerOneMillion': 62634,
  'deathsPerOneMillion': 1766,
  'totalTests': 217800000,
  'testsPerOneMillion': 1491571},
 {'country': 'Turkey',
  'cases': 8457119,
  'todayCases': 25101,
  'deaths': 73973,
  'todayDeaths': 227,
  'recovered': 7941664,
  'active': 441482,
  'critical': 1405,
  'casesPerOneMillion': 98815,
  'deathsPerOneMillion': 864,
  'totalTests': 102663917,
  'testsPerOneMillion': 1199546},
 {'country': 'France',
  'cases': 7310664,
  'todayCases': 19778,
  'deaths': 118271,
  'todayDeaths': 47,
  'recovered': 7022070,
  'active': 170323,
  'critical': 1049,
  'casesPerOneMillion': 111661,
  'deathsPerOneMillion': 1806,
  'totalTests': 151204954,
  'testsPerOneMillion': 2309457},
 {'country': 'Iran',
  'cases': 6051642,
  'todayCases': 6430,
  'deaths': 128406,
  'todayDeaths': 134,
  'recovered': 5720893,
  'active': 202343,
  'critical': 3477,
  'casesPerOneMillion': 70805,
  'deathsPerOneMillion': 1502,
  'totalTests': 37254424,
  'testsPerOneMillion': 435881},
 {'country': 'Argentina',
  'cases': 5308781,
  'todayCases': 1622,
  'deaths': 116294,
  'todayDeaths': 44,
  'recovered': 5174548,
  'active': 17939,
  'critical': 578,
  'casesPerOneMillion': 116000,
  'deathsPerOneMillion': 2541,
  'totalTests': 25717039,
  'testsPerOneMillion': 561930},
 {'country': 'Germany',
  'cases': 5108904,
  'todayCases': 39985,
  'deaths': 98660,
  'todayDeaths': 299,
  'recovered': 4516000,
  'active': 494244,
  'critical': 2828,
  'casesPerOneMillion': 60710,
  'deathsPerOneMillion': 1172,
  'totalTests': 80348721,
  'testsPerOneMillion': 954802},
 {'country': 'Spain',
  'cases': 5061045,
  'todayCases': 4091,
  'deaths': 87745,
  'todayDeaths': 29,
  'recovered': 4896670,
  'active': 76630,
  'critical': 427,
  'casesPerOneMillion': 108189,
  'deathsPerOneMillion': 1876,
  'totalTests': 66213858,
  'testsPerOneMillion': 1415441},
 {'country': 'Colombia',
  'cases': 5036287,
  'todayCases': 2021,
  'deaths': 127865,
  'todayDeaths': 32,
  'recovered': 4877518,
  'active': 30904,
  'critical': 342,
  'casesPerOneMillion': 97550,
  'deathsPerOneMillion': 2477,
  'totalTests': 27465596,
  'testsPerOneMillion': 531992},
 {'country': 'Italy',
  'cases': 4873075,
  'todayCases': 7698,
  'deaths': 132893,
  'todayDeaths': 58,
  'recovered': 4616786,
  'active': 123396,
  'critical': 481,
  'casesPerOneMillion': 80761,
  'deathsPerOneMillion': 2202,
  'totalTests': 111735792,
  'testsPerOneMillion': 1851783},
 {'country': 'Indonesia',
  'cases': 4251423,
  'todayCases': 347,
  'deaths': 143685,
  'todayDeaths': 15,
  'recovered': 4099399,
  'active': 8339,
  'critical': 0,
  'casesPerOneMillion': 15321,
  'deathsPerOneMillion': 518,
  'totalTests': 50682476,
  'testsPerOneMillion': 182642},
 {'country': 'Mexico',
  'cases': 3846508,
  'todayCases': 775,
  'deaths': 291204,
  'todayDeaths': 57,
  'recovered': 3209863,
  'active': 345441,
  'critical': 4798,
  'casesPerOneMillion': 29409,
  'deathsPerOneMillion': 2226,
  'totalTests': 11600384,
  'testsPerOneMillion': 88692},
 {'country': 'Ukraine',
  'cases': 3244749,
  'todayCases': 16308,
  'deaths': 77985,
  'todayDeaths': 838,
  'recovered': 2664373,
  'active': 502391,
  'critical': 177,
  'casesPerOneMillion': 74811,
  'deathsPerOneMillion': 1798,
  'totalTests': 15292648,
  'testsPerOneMillion': 352590},
 {'country': 'Poland',
  'cases': 3230634,
  'todayCases': 16590,
  'deaths': 79161,
  'todayDeaths': 282,
  'recovered': 2827027,
  'active': 324446,
  'critical': 1270,
  'casesPerOneMillion': 85490,
  'deathsPerOneMillion': 2095,
  'totalTests': 23113362,
  'testsPerOneMillion': 611633},
 {'country': 'South Africa',
  'cases': 2926348,
  'todayCases': 273,
  'deaths': 89504,
  'todayDeaths': 15,
  'recovered': 2820030,
  'active': 16814,
  'critical': 546,
  'casesPerOneMillion': 48501,
  'deathsPerOneMillion': 1483,
  'totalTests': 18962806,
  'testsPerOneMillion': 314289},
 {'country': 'Philippines',
  'cases': 2819341,
  'todayCases': 849,
  'deaths': 45808,
  'todayDeaths': 99,
  'recovered': 2748069,
  'active': 25464,
  'critical': 1253,
  'casesPerOneMillion': 25267,
  'deathsPerOneMillion': 411,
  'totalTests': 23675873,
  'testsPerOneMillion': 212180},
 {'country': 'Malaysia',
  'cases': 2556865,
  'todayCases': 5413,
  'deaths': 29769,
  'todayDeaths': 40,
  'recovered': 2461780,
  'active': 65316,
  'critical': 545,
  'casesPerOneMillion': 77633,
  'deathsPerOneMillion': 904,
  'totalTests': 36005549,
  'testsPerOneMillion': 1093215},
 {'country': 'Netherlands',
  'cases': 2334472,
  'todayCases': 20168,
  'deaths': 18785,
  'todayDeaths': 35,
  'recovered': 2028961,
  'active': 286726,
  'critical': 376,
  'casesPerOneMillion': 135828,
  'deathsPerOneMillion': 1093,
  'totalTests': 19205114,
  'testsPerOneMillion': 1117421},
 {'country': 'Peru',
  'cases': 2215373,
  'todayCases': 0,
  'deaths': 200672,
  'todayDeaths': 0,
  'recovered': None,
  'active': None,
  'critical': 907,
  'casesPerOneMillion': 65929,
  'deathsPerOneMillion': 5972,
  'totalTests': 19664890,
  'testsPerOneMillion': 585221},
 {'country': 'Iraq',
  'cases': 2070883,
  'todayCases': 807,
  'deaths': 23562,
  'todayDeaths': 26,
  'recovered': 2027560,
  'active': 19761,
  'critical': 139,
  'casesPerOneMillion': 49948,
  'deathsPerOneMillion': 568,
  'totalTests': 16097977,
  'testsPerOneMillion': 388273},
 {'country': 'Thailand',
  'cases': 2030700,
  'todayCases': 5947,
  'deaths': 20141,
  'todayDeaths': 62,
  'recovered': 1918452,
  'active': 92107,
  'critical': 1776,
  'casesPerOneMillion': 28993,
  'deathsPerOneMillion': 288,
  'totalTests': 14913135,
  'testsPerOneMillion': 212921},
 {'country': 'Czechia',
  'cases': 1907629,
  'todayCases': 11514,
  'deaths': 31636,
  'todayDeaths': 45,
  'recovered': 1725968,
  'active': 150025,
  'critical': 635,
  'casesPerOneMillion': 177680,
  'deathsPerOneMillion': 2947,
  'totalTests': 42055310,
  'testsPerOneMillion': 3917116},
 {'country': 'Canada',
  'cases': 1754047,
  'todayCases': 1530,
  'deaths': 29390,
  'todayDeaths': 6,
  'recovered': 1700765,
  'active': 23892,
  'critical': 545,
  'casesPerOneMillion': 45921,
  'deathsPerOneMillion': 769,
  'totalTests': 47540334,
  'testsPerOneMillion': 1244616},
 {'country': 'Romania',
  'cases': 1748568,
  'todayCases': 4128,
  'deaths': 53661,
  'todayDeaths': 343,
  'recovered': 1598656,
  'active': 96251,
  'critical': 1681,
  'casesPerOneMillion': 91735,
  'deathsPerOneMillion': 2815,
  'totalTests': 15509313,
  'testsPerOneMillion': 813660},
 {'country': 'Chile',
  'cases': 1730456,
  'todayCases': 1689,
  'deaths': 38005,
  'todayDeaths': 4,
  'recovered': 1632749,
  'active': 59702,
  'critical': 599,
  'casesPerOneMillion': 89468,
  'deathsPerOneMillion': 1965,
  'totalTests': 24633609,
  'testsPerOneMillion': 1273604},
 {'country': 'Japan',
  'cases': 1725561,
  'todayCases': 79,
  'deaths': 18327,
  'todayDeaths': 0,
  'recovered': 1705666,
  'active': 1568,
  'critical': 82,
  'casesPerOneMillion': 13701,
  'deathsPerOneMillion': 146,
  'totalTests': 27223924,
  'testsPerOneMillion': 216159},
 {'country': 'Bangladesh',
  'cases': 1572948,
  'todayCases': 213,
  'deaths': 27928,
  'todayDeaths': 2,
  'recovered': 1536967,
  'active': 8053,
  'critical': 1400,
  'casesPerOneMillion': 9422,
  'deathsPerOneMillion': 167,
  'totalTests': 10634254,
  'testsPerOneMillion': 63700},
 {'country': 'Belgium',
  'cases': 1512474,
  'todayCases': 9229,
  'deaths': 26403,
  'todayDeaths': 27,
  'recovered': 1253548,
  'active': 232523,
  'critical': 471,
  'casesPerOneMillion': 129726,
  'deathsPerOneMillion': 2265,
  'totalTests': 23022800,
  'testsPerOneMillion': 1974689},
 {'country': 'Israel',
  'cases': 1338233,
  'todayCases': 346,
  'deaths': 8148,
  'todayDeaths': 5,
  'recovered': 1324000,
  'active': 6085,
  'critical': 134,
  'casesPerOneMillion': 143495,
  'deathsPerOneMillion': 874,
  'totalTests': 30655451,
  'testsPerOneMillion': 3287095},
 {'country': 'Pakistan',
  'cases': 1280092,
  'todayCases': 216,
  'deaths': 28618,
  'todayDeaths': 6,
  'recovered': 1228848,
  'active': 22626,
  'critical': 1101,
  'casesPerOneMillion': 5645,
  'deathsPerOneMillion': 126,
  'totalTests': 21452460,
  'testsPerOneMillion': 94597},
 {'country': 'Serbia',
  'cases': 1218423,
  'todayCases': 3773,
  'deaths': 10951,
  'todayDeaths': 55,
  'recovered': 1114763,
  'active': 92709,
  'critical': 267,
  'casesPerOneMillion': 140226,
  'deathsPerOneMillion': 1260,
  'totalTests': 6603023,
  'testsPerOneMillion': 759932},
 {'country': 'Sweden',
  'cases': 1185093,
  'todayCases': 0,
  'deaths': 15063,
  'todayDeaths': 0,
  'recovered': 1147441,
  'active': 22589,
  'critical': 32,
  'casesPerOneMillion': 116348,
  'deathsPerOneMillion': 1479,
  'totalTests': 13485270,
  'testsPerOneMillion': 1323928},
 {'country': 'Portugal',
  'cases': 1110155,
  'todayCases': 1693,
  'deaths': 18274,
  'todayDeaths': 9,
  'recovered': 1053609,
  'active': 38272,
  'critical': 80,
  'casesPerOneMillion': 109312,
  'deathsPerOneMillion': 1799,
  'totalTests': 20385083,
  'testsPerOneMillion': 2007231},
 {'country': 'Vietnam',
  'cases': 1045397,
  'todayCases': 10259,
  'deaths': 23270,
  'todayDeaths': 87,
  'recovered': 870997,
  'active': 151130,
  'critical': 4101,
  'casesPerOneMillion': 10609,
  'deathsPerOneMillion': 236,
  'totalTests': 64714626,
  'testsPerOneMillion': 656722},
 {'country': 'Austria',
  'cases': 981904,
  'todayCases': 10363,
  'deaths': 11807,
  'todayDeaths': 61,
  'recovered': 850926,
  'active': 119171,
  'critical': 458,
  'casesPerOneMillion': 108175,
  'deathsPerOneMillion': 1301,
  'totalTests': 104177857,
  'testsPerOneMillion': 11477098},
 {'country': 'Hungary',
  'cases': 966167,
  'todayCases': 5325,
  'deaths': 32336,
  'todayDeaths': 165,
  'recovered': 827237,
  'active': 106594,
  'critical': 545,
  'casesPerOneMillion': 100364,
  'deathsPerOneMillion': 3359,
  'totalTests': 7876457,
  'testsPerOneMillion': 818196},
 {'country': 'Cuba',
  'cases': 959307,
  'todayCases': 243,
  'deaths': 8284,
  'todayDeaths': 1,
  'recovered': 949340,
  'active': 1683,
  'critical': 52,
  'casesPerOneMillion': 84766,
  'deathsPerOneMillion': 732,
  'totalTests': 10831678,
  'testsPerOneMillion': 957106},
 {'country': 'Kazakhstan',
  'cases': 958468,
  'todayCases': 931,
  'deaths': 12450,
  'todayDeaths': 16,
  'recovered': 916872,
  'active': 29146,
  'critical': 528,
  'casesPerOneMillion': 50221,
  'deathsPerOneMillion': 652,
  'totalTests': 11575012,
  'testsPerOneMillion': 606492},
 {'country': 'Morocco',
  'cases': 948391,
  'todayCases': 120,
  'deaths': 14747,
  'todayDeaths': 1,
  'recovered': 930379,
  'active': 3265,
  'critical': 347,
  'casesPerOneMillion': 25283,
  'deathsPerOneMillion': 393,
  'totalTests': 10279270,
  'testsPerOneMillion': 274030},
 {'country': 'Switzerland',
  'cases': 923037,
  'todayCases': 4297,
  'deaths': 11369,
  'todayDeaths': 3,
  'recovered': 845400,
  'active': 66268,
  'critical': 125,
  'casesPerOneMillion': 105591,
  'deathsPerOneMillion': 1301,
  'totalTests': 12199175,
  'testsPerOneMillion': 1395533},
 {'country': 'Jordan',
  'cases': 898682,
  'todayCases': 3118,
  'deaths': 11279,
  'todayDeaths': 24,
  'recovered': 855172,
  'active': 32231,
  'critical': 743,
  'casesPerOneMillion': 86894,
  'deathsPerOneMillion': 1091,
  'totalTests': 11555786,
  'testsPerOneMillion': 1117334},
 {'country': 'Greece',
  'cases': 847188,
  'todayCases': 8129,
  'deaths': 16923,
  'todayDeaths': 85,
  'recovered': 750538,
  'active': 79727,
  'critical': 547,
  'casesPerOneMillion': 81830,
  'deathsPerOneMillion': 1635,
  'totalTests': 31171430,
  'testsPerOneMillion': 3010850},
 {'country': 'Nepal',
  'cases': 817672,
  'todayCases': 339,
  'deaths': 11482,
  'todayDeaths': 4,
  'recovered': 798714,
  'active': 7476,
  'critical': 0,
  'casesPerOneMillion': 27387,
  'deathsPerOneMillion': 385,
  'totalTests': 4520580,
  'testsPerOneMillion': 151413},
 {'country': 'Georgia',
  'cases': 791115,
  'todayCases': 5204,
  'deaths': 11140,
  'todayDeaths': 83,
  'recovered': 727184,
  'active': 52791,
  'critical': 0,
  'casesPerOneMillion': 198841,
  'deathsPerOneMillion': 2800,
  'totalTests': 10952279,
  'testsPerOneMillion': 2752771},
 {'country': 'UAE',
  'cases': 741074,
  'todayCases': 68,
  'deaths': 2144,
  'todayDeaths': 0,
  'recovered': 735723,
  'active': 3207,
  'critical': 0,
  'casesPerOneMillion': 73706,
  'deathsPerOneMillion': 213,
  'totalTests': 97258646,
  'testsPerOneMillion': 9673127},
 {'country': 'Tunisia',
  'cases': 715818,
  'todayCases': 102,
  'deaths': 25320,
  'todayDeaths': 5,
  'recovered': 689639,
  'active': 859,
  'critical': 58,
  'casesPerOneMillion': 59709,
  'deathsPerOneMillion': 2112,
  'totalTests': 3128507,
  'testsPerOneMillion': 260959},
 {'country': 'Bulgaria',
  'cases': 662739,
  'todayCases': 3869,
  'deaths': 26676,
  'todayDeaths': 121,
  'recovered': 524401,
  'active': 111662,
  'critical': 767,
  'casesPerOneMillion': 96377,
  'deathsPerOneMillion': 3879,
  'totalTests': 6157900,
  'testsPerOneMillion': 895500},
 {'country': 'Lebanon',
  'cases': 654068,
  'todayCases': 1102,
  'deaths': 8596,
  'todayDeaths': 8,
  'recovered': 625313,
  'active': 20159,
  'critical': 186,
  'casesPerOneMillion': 96422,
  'deathsPerOneMillion': 1267,
  'totalTests': 4795578,
  'testsPerOneMillion': 706957},
 {'country': 'Belarus',
  'cases': 631025,
  'todayCases': 1754,
  'deaths': 4875,
  'todayDeaths': 14,
  'recovered': 611204,
  'active': 14946,
  'critical': 0,
  'casesPerOneMillion': 66810,
  'deathsPerOneMillion': 516,
  'totalTests': 10062789,
  'testsPerOneMillion': 1065404},
 {'country': 'Guatemala',
  'cases': 610591,
  'todayCases': 557,
  'deaths': 15749,
  'todayDeaths': 19,
  'recovered': 592590,
  'active': 2252,
  'critical': 5,
  'casesPerOneMillion': 33238,
  'deathsPerOneMillion': 857,
  'totalTests': 3026849,
  'testsPerOneMillion': 164768},
 {'country': 'Slovakia',
  'cases': 569866,
  'todayCases': 6421,
  'deaths': 13644,
  'todayDeaths': 46,
  'recovered': 474318,
  'active': 81904,
  'critical': 499,
  'casesPerOneMillion': 104308,
  'deathsPerOneMillion': 2497,
  'totalTests': 4256482,
  'testsPerOneMillion': 779108},
 {'country': 'Costa Rica',
  'cases': 564901,
  'todayCases': 239,
  'deaths': 7231,
  'todayDeaths': 8,
  'recovered': 534171,
  'active': 23499,
  'critical': 148,
  'casesPerOneMillion': 109519,
  'deathsPerOneMillion': 1402,
  'totalTests': 2575363,
  'testsPerOneMillion': 499292},
 {'country': 'Azerbaijan',
  'cases': 563940,
  'todayCases': 2015,
  'deaths': 7502,
  'todayDeaths': 31,
  'recovered': 525838,
  'active': 30600,
  'critical': 0,
  'casesPerOneMillion': 54940,
  'deathsPerOneMillion': 731,
  'totalTests': 5380154,
  'testsPerOneMillion': 524140},
 {'country': 'Sri Lanka',
  'cases': 552994,
  'todayCases': 720,
  'deaths': 14034,
  'todayDeaths': 18,
  'recovered': 524740,
  'active': 14220,
  'critical': 0,
  'casesPerOneMillion': 25677,
  'deathsPerOneMillion': 652,
  'totalTests': 5500800,
  'testsPerOneMillion': 255416},
 {'country': 'Saudi Arabia',
  'cases': 549297,
  'todayCases': 37,
  'deaths': 8818,
  'todayDeaths': 2,
  'recovered': 538373,
  'active': 2106,
  'critical': 50,
  'casesPerOneMillion': 15448,
  'deathsPerOneMillion': 248,
  'totalTests': 30863762,
  'testsPerOneMillion': 867979},
 {'country': 'Croatia',
  'cases': 544330,
  'todayCases': 4443,
  'deaths': 9986,
  'todayDeaths': 50,
  'recovered': 500584,
  'active': 33760,
  'critical': 289,
  'casesPerOneMillion': 133727,
  'deathsPerOneMillion': 2453,
  'totalTests': 3288144,
  'testsPerOneMillion': 807809},
 {'country': 'Bolivia',
  'cases': 524261,
  'todayCases': 776,
  'deaths': 19022,
  'todayDeaths': 5,
  'recovered': 483330,
  'active': 21909,
  'critical': 220,
  'casesPerOneMillion': 44086,
  'deathsPerOneMillion': 1600,
  'totalTests': 2563530,
  'testsPerOneMillion': 215574},
 {'country': 'Ecuador',
  'cases': 521792,
  'todayCases': 0,
  'deaths': 33088,
  'todayDeaths': 0,
  'recovered': 443880,
  'active': 44824,
  'critical': 759,
  'casesPerOneMillion': 28971,
  'deathsPerOneMillion': 1837,
  'totalTests': 1917796,
  'testsPerOneMillion': 106480},
 {'country': 'Myanmar',
  'cases': 514716,
  'todayCases': 754,
  'deaths': 18963,
  'todayDeaths': 17,
  'recovered': 486126,
  'active': 9627,
  'critical': 0,
  'casesPerOneMillion': 9374,
  'deathsPerOneMillion': 345,
  'totalTests': 5259819,
  'testsPerOneMillion': 95788},
 {'country': 'Ireland',
  'cases': 507413,
  'todayCases': 4395,
  'deaths': 5566,
  'todayDeaths': 0,
  'recovered': 411085,
  'active': 90762,
  'critical': 117,
  'casesPerOneMillion': 101208,
  'deathsPerOneMillion': 1110,
  'totalTests': 8523650,
  'testsPerOneMillion': 1700124},
 {'country': 'Panama',
  'cases': 474735,
  'todayCases': 0,
  'deaths': 7346,
  'todayDeaths': 0,
  'recovered': 465541,
  'active': 1848,
  'critical': 49,
  'casesPerOneMillion': 107698,
  'deathsPerOneMillion': 1667,
  'totalTests': 4143540,
  'testsPerOneMillion': 940002},
 {'country': 'Paraguay',
  'cases': 462059,
  'todayCases': 56,
  'deaths': 16342,
  'todayDeaths': 2,
  'recovered': 445028,
  'active': 689,
  'critical': 43,
  'casesPerOneMillion': 63707,
  'deathsPerOneMillion': 2253,
  'totalTests': 1923260,
  'testsPerOneMillion': 265173},
 {'country': 'Lithuania',
  'cases': 446120,
  'todayCases': 1915,
  'deaths': 6375,
  'todayDeaths': 23,
  'recovered': 406270,
  'active': 33475,
  'critical': 155,
  'casesPerOneMillion': 167085,
  'deathsPerOneMillion': 2388,
  'totalTests': 5879438,
  'testsPerOneMillion': 2202017},
 {'country': 'Denmark',
  'cases': 430891,
  'todayCases': 3899,
  'deaths': 2781,
  'todayDeaths': 9,
  'recovered': 389395,
  'active': 38715,
  'critical': 44,
  'casesPerOneMillion': 74033,
  'deathsPerOneMillion': 478,
  'totalTests': 89319132,
  'testsPerOneMillion': 15346300},
 {'country': 'Palestine',
  'cases': 427121,
  'todayCases': 87,
  'deaths': 4496,
  'todayDeaths': 3,
  'recovered': 419679,
  'active': 2946,
  'critical': 45,
  'casesPerOneMillion': 81139,
  'deathsPerOneMillion': 854,
  'totalTests': 2686972,
  'testsPerOneMillion': 510438},
 {'country': 'Venezuela',
  'cases': 420500,
  'todayCases': 0,
  'deaths': 5034,
  'todayDeaths': 0,
  'recovered': 406666,
  'active': 8800,

In [136]:
df_covid = spark.read.json(sc.parallelize(r.json()))

In [139]:
df_covid.select('country','deaths').show()

+------------+-------+
|     country| deaths|
+------------+-------+
|       World|5129233|
|         USA| 786236|
|       India| 463852|
|      Brazil| 611524|
|          UK| 143159|
|      Russia| 257837|
|      Turkey|  73973|
|      France| 118271|
|        Iran| 128406|
|   Argentina| 116294|
|     Germany|  98660|
|       Spain|  87745|
|    Colombia| 127865|
|       Italy| 132893|
|   Indonesia| 143685|
|      Mexico| 291204|
|     Ukraine|  77985|
|      Poland|  79161|
|South Africa|  89504|
| Philippines|  45808|
+------------+-------+
only showing top 20 rows